security:
    role_hierarchy:
        ROLE_MODERATOR:      ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                #failure_handler: my_bundle.failure.login.handler
                success_handler: my_bundle.success.login.handler
            logout:       true
            anonymous:    true
